import {
    LuChevronUp, LuDownload, LuSettings, LuMenu, LuSearch, LuEllipsis, LuContact, LuMonitor,
    LuBell, LuLayoutDashboard, LuBuilding, LuBuilding2, LuReplace,
    LuListChecks, LuHeadset, LuCircleHelp, LuClipboard, LuClipboardList, LuFileText, LuUsers,
    LuTable, LuKeyRound, LuCalendar, LuSheet, LuRefreshCw, LuX, LuCheck, LuCircleCheck, LuCalendarClock,
    LuSmartphone, LuMonitorSmartphone, LuUndo2, LuReceipt, LuUnfoldVertical, LuFoldVertical,
    LuLoader, LuCopy, LuShare, LuCircle, LuGithub, LuPlay, LuPause, LuShoppingBag,
    LuArrowUpDown, LuCode, LuPackage, LuStore, LuGlobe, LuPercent,
    LuSun, LuMoon, LuCloudUpload, LuMap, LuClock, LuTruck, LuCreditCard,
    LuPanelRightClose, LuPanelRightOpen, LuCalendarPlus
} from 'react-icons/lu'
import { BsFileEarmarkExcel } from 'react-icons/bs'

export const adminIcons = {
    download: LuDownload,
    settings: LuSettings,
    menu: LuMenu,
    search: LuSearch,
    options: LuEllipsis,
    persons: LuContact,
    desktop: LuMonitor,
    notifications: LuBell,
    dashboard: LuLayoutDashboard,
    buildings: LuBuilding2,
    building: LuBuilding,
    replace: LuReplace,
    placement: LuListChecks,
    tasks: LuHeadset,
    question: LuCircleHelp,
    clipboard: LuClipboard,
    clipboardList: LuClipboardList,
    reports: LuFileText,
    users: LuUsers,
    table: LuTable,
    key: LuKeyRound,
    calendar: LuCalendar,
    csv: BsFileEarmarkExcel,
    refresh: LuRefreshCw,
    x: LuX,
    v: LuCheck,
    payRepeat: LuCalendarClock,
    asign: LuSmartphone,
    release: LuMonitorSmartphone,
    refund: LuUndo2,
    receipt: LuReceipt,
    expand: LuUnfoldVertical,
    collapse: LuFoldVertical,
    load: LuLoader,
    copy: LuCopy,
    share: LuShare,
    calendarAdd: LuCalendarPlus,
    check: LuCircleCheck,
    checkEmpty: LuCircle,
    github: LuGithub,
    play: LuPlay,
    pause: LuPause,
    sortUp: LuChevronUp,
    sortDown: LuChevronDown,
    log: LuCode,
    products: LuPackage,
    orders: LuShoppingBag,
    stores: LuStore,
    domains: LuGlobe,
    sale: LuPercent,
    toMini: LuPanelRightClose,
    unMini: LuPanelRightOpen,
    darkMode: LuMoon,
    lightMode: LuSun,
    sync: LuCloudUpload,
    map: LuMap,
    time: LuClock,
    bag: LuShoppingBag,
    truck: LuTruck,
    card: LuCreditCard
}
